[alias]
c = "check"
be = "build --example"
ee = "embed --example"
oe = "objcopy --example"

blinky = "be blinky"
blinky-probe = "ee blinky"
blinky-bin = "oe blinky --release -- -O binary target/thumbv7em-none-eabihf/release/examples/blinky.bin"

serial = "be serial"
serial-probe = "ee serial"
serial-bin = "oe serial --release -- -O binary target/thumbv7em-none-eabihf/release/examples/serial.bin"

usb-serial = "be usb_serial --features=usb"
usb-serial-probe = "ee usb_serial --features=usb"
usb-serial-bin = "oe usb_serial --release --features=usb -- -O binary target/thumbv7em-none-eabihf/release/examples/usb_serial.bin"

[build]
target = "thumbv7em-none-eabihf" # Cortex-M4F and Cortex-M7F (with FPU)

rustflags = [
  # Use LLD as the default linker
  "-C",
  "link-arg=-Tlink.x",
  "-C",
  "link-arg=--nmagic",
  "-C",
  "link-arg=-Tdefmt.x",
]

[env]
DEFMT_LOG = "info"
